export const ERROR_CODES: any = {
  CREATE_SUCCESSFULLY: 'CREATE SUCCESSFULLY',
  DELETE_SUCCESSFULLY: 'DELETE SUCCESSFULLY',
  UPDATE_SUCCESSFULLY: 'UPDATE SUCCESSFULLY',
  BAD_REQUEST: 'Bad Request',
  VALIDATION_FAILED: 'VALIDATION FAILED',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_PASSWORD: 'Password invalid',
  INVALID_EMAIL: 'Email invalid',
  USER_NOT_FOUND: 'Not found user',
  DATA_NOT_FOUND: 'Data not found',
  STATUS_DEFAULT: 'Status default not found',
  CID_NOT_FOUND: 'Cid not found',
  CID_MAX_LENGTH: 'Cid over limit',
  BILLINGTYPE_DEFAULT: 'Billing type default not found',
  OVERFLOW_CODE: 'Overflow code',
  USER_NOT_FIND: 'Can not find User order by ID',
  CAN_NOT_UPDATE_ATTENDANCE: 'Your cannot update this attendance again , contact admin',
  LOCATION_NOT_FAIL: 'You fail your location',
  ATTENDANCE_ERR : 'you already checked in before',
  CANT_ATTENDANCE_TODAY: 'You can not attendance this day',
  CANT_CREATE_ONLEAVE_HAS_FOUND : 'You can not create this onLeave because it has found',
  START_TIME_SMALLER_THAN_END_TIME: 'Start Time must be small than End Time',
  NOT_FOUND : 'This match not Found',
  YOU_CANNOT_DO_THIS_ACTION_BECAUSE_STATUS: 'You cannot do this action because status',
}
